version: 2

# Default node.js image
defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:10.13.0-stretch

# Filter only tagged commit
filter_version_tag: &filter_version_tag
  filters:
    tags:
      only: /v[0-9]+(\.[0-9]+)*/
    branches:
      ignore: /.*/

jobs:
  # Checkout code, install dependencies and save cache
  checkout:
    <<: *defaults

    steps:
      - checkout

      - restore_cache:
          name: Restore node_modules cache
          keys:
            - v1-dependencies-{{ arch }}-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - v1-dependencies-{{ arch }}-{{ .Branch }}-
            - v1-dependencies-{{ arch }}-

      - run:
          name: Install dependencies
          command: npm ci

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ arch }}-{{ .Branch }}-{{ checksum "package-lock.json" }}

      - persist_to_workspace:
          root: ~/repo
          paths: .

  # Build
  build:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/repo

      - run:
          name: Build
          command: npm run build

      - persist_to_workspace:
          root: ~/repo
          paths: .

  # Run tests and sanity checks
  test:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/repo

      - run:
          name: Testing
          command: npm test

  # Deploy package to npm
  deploy:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/repo

      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc

      - run:
          name: Publish package to npm
          command: npm publish

workflows:
  version: 2

  build:
    jobs:
      - checkout

      - build:
          requires:
            - checkout

      - test:
          requires:
            - build

  release:
    jobs:
      - checkout:
          <<: *filter_version_tag

      - build:
          <<: *filter_version_tag
          requires:
            - checkout

      - test:
          <<: *filter_version_tag
          requires:
            - build

      - release:
          <<: *filter_version_tag
          requires:
            - test