#!/usr/bin/env node

const https = require('https');

const GITHUB_API_URL = 'https://api.github.com';
const GITHUB_TOKEN = '';


https.get(`${GITHUB_API_URL}/mtronix/hookon`, response => {
  console.log(response.statusCode);
});

console.log('Hello bin script' + GITHUB_TOKEN);